opendigitaleducation/ode-react-ui

.changeset/orange-chicken-sleep.md
libs/core/README.md
libs/core/package.json
libs/core/src/Button/Button.tsx

fix(core): add wai aria documentation to button component

---

.changeset/unlucky-poems-compare.md
libs/advanced/package.json
libs/advanced/src/TreeView/TreeView.tsx

fix(advanced): change icons components in TreeView

---

.changeset/famous-bananas-burn.md
libs/icons/README.md

chore(icons): update readme file

---

config/prettier-config-custom/prettier.config.js
config/vite/vite.config.ts

chore(config): update prettier and vite config

---

.changeset/giant-years-leave.md
libs/core/src/Button/Button.stories.tsx
libs/core/src/Button/Button.tsx
libs/core/src/Button/ButtonProps.tsx
libs/core/src/Button/LoadingButton.tsx

feat(core): add new components button with stories and interfaces

---

.changeset/wicked-pugs-kick.md
config/vite/vite.config.ts

chore(build): #WB2-129, add apps icons to external deps

---

.changeset/four-toys-reply.md

update deps, fix css components and add useThemeHelper hook

---

.changeset/four-toys-reply.md
.github/workflows/pre-release.yml
.github/workflows/release.yml
README.md
docs/README.md
docs/package.json
package.json
packages/advanced/package.json
packages/core/package.json
packages/core/src/Header/Header.tsx
packages/hooks/package.json
packages/hooks/src/useToggle/useToggle.ts
packages/icons/package.json
yarn.lock

chore(deps): update deps and update readme

---

packages/core/src/Modal/Modal.stories.tsx

Derniers retours sur tickets WB2-178. Modal Partage
- [ ] Icons
- [ ] Config
>
>

fix(modal): WB2-178 part 2

---

.changeset/four-walls-melt.md
packages/core/src/Modal/Modal.tsx
packages/core/src/Modal/ModalBody.tsx
packages/core/src/Modal/ModalFooter.tsx
packages/core/src/Modal/ModalHeader.tsx
packages/core/src/Modal/ModalSubtitle.tsx

fix(core): rename displayName modal for compound component

---

.changeset/four-walls-melt.md
.changeset/witty-poets-brush.md
packages/core/src/Form/FormControl.stories.tsx
packages/core/src/Form/FormControl.tsx
packages/core/src/Modal/Modal.tsx
packages/core/src/Modal/ModalBody.tsx
packages/core/src/Modal/ModalFooter.tsx
packages/core/src/Modal/ModalHeader.tsx
packages/core/src/Modal/ModalSubtitle.tsx

fix issue with displayname for compound components

---

.changeset/thirty-games-watch.md
packages/core/package.json
packages/core/src/Form/Select.tsx
packages/core/src/Modal/Modal.stories.tsx
yarn.lock

fix(select): remove placeholder and add default disabled option

---

packages/core/src/Modal/Modal.stories.tsx

fix(modal): spacing between formcontrol

---

.changeset/brown-files-help.md
packages/hooks/package.json
packages/hooks/src/index.ts
packages/hooks/src/useHotToast/index.ts
packages/hooks/src/useHotToast/useHotToast.docs.mdx
packages/hooks/src/useHotToast/useHotToast.stories.tsx
packages/hooks/src/useHotToast/useHotToast.tsx

Add Hot Toast hook for user notifications.
Hot Toast hook is based on React Hot Toast.
https://opendigitaleducation.atlassian.net/browse/WB2-64
- [ ] Icons
- [ ] Config
>
>

#WB2-64, Add useHotToast Hook

---

packages/core/src/Dropdown/Dropdown.stories.tsx
packages/core/src/Dropdown/Dropdown.tsx
packages/core/src/Dropdown/DropdownTrigger.tsx
packages/core/src/Dropdown/DropdownTriggerProps.ts

Fix some layout issues. Add animation.
- [ ] Icons
- [ ] Config
>
>

fix: Dropdown layout

---

packages/core/src/Library/Library.tsx

feat(core): #WB2-27, add storybook component library

---

.changeset/healthy-taxis-double.md
packages/core/src/Library/Library.tsx

feat(core): #WB2-72, add redirection library composant

---

.changeset/breezy-plants-brush.md
packages/core/src/VisuallyHidden/VisuallyHidden.tsx
packages/core/src/index.ts

feat(core): add visually-hidden component

---

.changeset/strange-doors-wave.md
packages/hooks/src/useModal/useModal.ts

feat(hooks), #WB2-573, integration modal onboarding trash

---

.changeset/sweet-roses-appear.md
packages/advanced/src/TreeView/TreeView.tsx
packages/core/src/EmptyScreen/EmptyScreen.tsx

fix(folder): #WB2-587, folder root selected default on app

---

.changeset/calm-parents-juggle.md
packages/core/src/Card/Card.tsx

fix(card): #WB2-627, add width and height img composant card

---

.changeset/famous-phones-look.md
packages/advanced/src/Header/Header.tsx

fix(advanced): #WB2-613, fix url header appli, ma classe

---

.changeset/yellow-parents-dance.md
packages/core/src/Modal/Modal.stories.tsx
packages/core/src/Modal/Modal.tsx
packages/core/src/Modal/ModalContext.tsx
packages/core/src/Modal/ModalHeader.tsx
packages/core/src/Modal/ModalProps.ts

Add Modal default focus param
- [ ] Icons
- [ ] Config
>
>

#WB2-701, Add Modal default focus param

---

.changeset/ninety-files-cry.md
packages/advanced/src/Layout/Layout.tsx
packages/core/src/AppCard/AppCardContext.tsx
packages/core/src/AppCard/AppName.tsx
packages/core/src/Grid/Grid.stories.tsx
packages/core/src/Grid/Grid.tsx
packages/core/src/Grid/index.ts
packages/core/src/OdeClientProvider/OdeClientProvider.tsx
packages/core/src/OdeClientProvider/index.ts
packages/core/src/Popover/Popover.tsx
packages/core/src/Popover/index.ts
packages/hooks/src/useHover/useHover.stories.tsx

fix: #WB2-835, layout flex size

---

.changeset/heavy-dolphins-poke.md
packages/components/src/index.ts

fix(core): add export component tooltip

---

.changeset/shaggy-gifts-itch.md
packages/core/src/index.ts
packages/core/src/useIsAdml/index.ts
packages/core/src/useIsAdml/useIsAdml.ts

Add isAdml Hook.
- [ ] Icons
>
>

Add isAdml Hook

---

.changeset/great-ties-boil.md
packages/components/src/Card/Card.tsx

fix(core): add padding card component

---

.changeset/ninety-mayflies-boil.md
packages/hooks/src/useScrollToTop/useScrollToTop.mdx
packages/hooks/src/useScrollToTop/useScrollToTop.stories.tsx

fix(hooks): add story mdx hook ScrollToTop
